### ISSUE TITLE
Doesn't work unless you provide a `--pk`

### ISSUE THREAD

**Issue by simonw** [simonw/yaml-to-sqlite#3]
Probably due to a `sqlite-utils` change from a while ago.
```
yaml-to-sqlite news.db news news.yaml
Traceback (most recent call last):
  File "/Users/simon/.local/share/virtualenvs/datasette.io-TK86ygSO/bin/yaml-to-sqlite", line 8, in <module>
    sys.exit(cli())
  File "/Users/simon/.local/share/virtualenvs/datasette.io-TK86ygSO/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/simon/.local/share/virtualenvs/datasette.io-TK86ygSO/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/simon/.local/share/virtualenvs/datasette.io-TK86ygSO/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/simon/.local/share/virtualenvs/datasette.io-TK86ygSO/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/simon/.local/share/virtualenvs/datasette.io-TK86ygSO/lib/python3.9/site-packages/yaml_to_sqlite/cli.py", line 22, in cli
    db[table].upsert_all(docs, pk=pk)
  File "/Users/simon/.local/share/virtualenvs/datasette.io-TK86ygSO/lib/python3.9/site-packages/sqlite_utils/db.py", line 1824, in upsert_all
    return self.insert_all(
  File "/Users/simon/.local/share/virtualenvs/datasette.io-TK86ygSO/lib/python3.9/site-packages/sqlite_utils/db.py", line 1702, in insert_all
    raise PrimaryKeyRequired("upsert() requires a pk")
sqlite_utils.db.PrimaryKeyRequired: upsert() requires a pk
```

**Comment by simonw** [comment]
The test already fails:
```
tmpdir = local('/private/var/folders/wr/hn3206rs1yzgq3r49bz8nvnh0000gn/T/pytest-of-simon/pytest-210/test_without_pk0')

    def test_without_pk(tmpdir):
        db_path = tmpdir / "db.db"
>       assert (
            0
            == CliRunner()
            .invoke(cli.cli, [str(db_path), "items", "-"], input=TEST_YAML)
            .exit_code
        )
E       AssertionError: assert 0 == 1
E        +  where 1 = <Result PrimaryKeyRequired('upsert() requires a pk')>.exit_code
E        +    where <Result PrimaryKeyRequired('upsert() requires a pk')> = <bound method CliRunner.invoke of <click.testing.CliRunner object at 0x10a08a518>>(<Command cli>, ['/private/var/folders/wr/hn3206rs1yzgq3r49bz8nvnh0000gn/T/pytest-of-simon/pytest-210/test_without_pk0/db.db', 'items', '-'], input='\n- name: datasette-cluster-map\n  url: https://github.com/simonw/datasette-cluster-map\n- name: datasette-vega\n  url: https://github.com/simonw/datasette-vega\n  nested_with_date:\n  - title: Hello\n    date: 2010-01-01\n')
E        +      where <bound method CliRunner.invoke of <click.testing.CliRunner object at 0x10a08a518>> = <click.testing.CliRunner object at 0x10a08a518>.invoke
E        +        where <click.testing.CliRunner object at 0x10a08a518> = CliRunner()
E        +      and   <Command cli> = cli.cli

tests/test_cli.py:32: AssertionError
```
